# Generated by Django 5.0.6 on 2024-08-31 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0007_rename_nombre_proyecto_modelanteproyecto_nombre_anteproyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRetroalimentacionesAnteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retroalimentacion', models.TextField(max_length=1000)),
                ('fecha_retroalimentacion', models.CharField(max_length=50)),
                ('doc_retroalimentacion', models.BinaryField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('aprobado_con_correcciones', 'Aprobado con correcciones'), ('rechazado', 'Rechazado')], default='aprobado', max_length=25)),
                ('anteproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones', to='estudiante.modelanteproyecto')),
            ],
        ),
    ]
