# Generated by Django 5.0.6 on 2024-09-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelretroalimentacionesanteproyecto',
            name='revs_dadas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
