# Generated by Django 5.1 on 2024-10-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfechascomite',
            name='periodo_academico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
