# Generated by Django 5.0.6 on 2024-09-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_modelretroalimentacionesanteproyecto_revs_dadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelretroalimentacionesanteproyecto',
            name='retroalimentacion',
            field=models.TextField(max_length=10000),
        ),
    ]
