# Generated by Django 5.1 on 2024-10-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_alter_modelfechascomite_periodo_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='tipo_solicitud',
            field=models.CharField(choices=[('cambio_nombre', 'Cambio de nombre del proyecto'), ('ajuste_integrantes', 'Ajuste de integrantes del proyecto'), ('cesion_derechos', 'Cesión de derechos del proyecto'), ('otro', 'Otro')], default='otro', max_length=200),
        ),
    ]
