# Generated by Django 5.0.6 on 2024-09-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_alter_modelretroalimentacionesanteproyecto_retroalimentacion'),
        ('estudiante', '0012_modelproyectofinal_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAsignacionJurados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jurado', models.CharField(max_length=50)),
                ('fecha_sustentacion', models.CharField(max_length=50)),
                ('proyecto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asignacion_Jurados', to='estudiante.modelproyectofinal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asignacion_Jurados', to='estudiante.modelanteproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRetroalimentaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retroalimentacion', models.TextField(max_length=10000)),
                ('fecha_retroalimentacion', models.CharField(max_length=50)),
                ('doc_retroalimentacion', models.BinaryField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('aprobado_con_correcciones', 'Aprobado con correcciones'), ('rechazado', 'Rechazado')], default='aprobado', max_length=25)),
                ('revs_dadas', models.IntegerField(blank=True, null=True)),
                ('anteproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='estudiante.modelanteproyecto')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='correspondencia.modelasignacionjurados')),
                ('proyecto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='estudiante.modelproyectofinal')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionEntregaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_presentacion_final', models.BinaryField(blank=True, null=True)),
                ('doc_proyecto_final', models.BinaryField(blank=True, null=True)),
                ('fecha_envio', models.CharField(max_length=50)),
                ('solicitud_enviada', models.BooleanField()),
                ('anteproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelanteproyecto')),
                ('proyecto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelproyectofinal')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelasignacionjurados')),
                ('retroalimentaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelretroalimentaciones')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelRetroalimentacionesAnteproyecto',
        ),
    ]
