# Generated by Django 5.0.6 on 2024-09-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_modelasignacionjurados_modelretroalimentaciones_and_more'),
        ('estudiante', '0012_modelproyectofinal_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInformacionEntregaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anteproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelanteproyecto')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelasignacionjurados')),
                ('proyecto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelproyectofinal')),
                ('retroalimentaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelretroalimentaciones')),
            ],
        ),
        migrations.DeleteModel(
            name='InformacionEntregaFinal',
        ),
    ]
