# Generated by Django 5.0.6 on 2024-09-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0005_modelinformacionentregafinal_and_more'),
        ('estudiante', '0014_alter_modelanteproyecto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelasignacionjurados',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignacion_Jurados', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelasignacionjurados',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignacion_Jurados', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelasignacionjurados'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='retroalimentaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelretroalimentaciones'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='correspondencia.modelasignacionjurados'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='estudiante.modelproyectofinal'),
        ),
    ]
