# Generated by Django 5.0.6 on 2024-09-07 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0007_alter_modelretroalimentaciones_estado'),
        ('estudiante', '0016_rename_coodirector_modelanteproyecto_codirector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacionado_con', models.CharField(blank=True, choices=[('anteproyecto', 'Anteproyecto'), ('proyecto_final', 'Proyecto Final')], max_length=255, null=True)),
                ('tipo_solicitud', models.CharField(choices=[('cambio_nombre', 'Cambio de nombre del proyecto'), ('ajuste_integrantes', 'Ajuste de integrantes del proyecto'), ('seccion_derechos', 'Sección de derechos del proyecto'), ('otro', 'Otro')], default='otro', max_length=200)),
                ('motivo_solicitud', models.TextField(max_length=10000)),
                ('documento_soporte', models.BinaryField(blank=True, null=True)),
                ('fecha_envio', models.CharField(max_length=50)),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Solicitudes', to='estudiante.modelanteproyecto')),
                ('proyecto_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Solicitudes', to='estudiante.modelproyectofinal')),
                ('retroalimentaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Solicitudes', to='correspondencia.modelretroalimentaciones')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
