# Generated by Django 5.0.6 on 2024-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0008_modelsolicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsolicitudes',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='relacionado_con',
            field=models.CharField(choices=[('anteproyecto', 'Anteproyecto'), ('proyecto_final', 'Proyecto Final')], default=True, max_length=255),
            preserve_default=False,
        ),
    ]
