# Generated by Django 5.0.6 on 2024-09-10 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_modelsolicitudes_estado_and_more'),
        ('estudiante', '0019_alter_modelproyectofinal_anteproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelasignacionjurados',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Asignacion_Jurados', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelasignacionjurados',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Asignacion_Jurados', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Informacion_Entrega_Final', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Informacion_Entrega_Final', to='correspondencia.modelasignacionjurados'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Informacion_Entrega_Final', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='retroalimentaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Informacion_Entrega_Final', to='correspondencia.modelretroalimentaciones'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Retroalimentaciones', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Retroalimentaciones', to='correspondencia.modelasignacionjurados'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Retroalimentaciones', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
