# Generated by Django 5.0.6 on 2024-09-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0011_rename_fecha_sustentacion_modelasignacionjurados_echa_sustentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelasignacionjurados',
            old_name='echa_sustentacion',
            new_name='fecha_sustentacion',
        ),
    ]
