# Generated by Django 5.0.6 on 2024-09-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0012_rename_echa_sustentacion_modelasignacionjurados_fecha_sustentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelasignacionjurados',
            name='fecha_sustentacion',
            field=models.DateField(max_length=50),
        ),
    ]
