# Generated by Django 5.0.6 on 2024-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0013_alter_modelasignacionjurados_fecha_sustentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='aprobado', max_length=25),
        ),
    ]
