# Generated by Django 5.0.6 on 2024-09-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0016_alter_modelinformacionentregafinal_jurado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='relacionado_con',
            field=models.CharField(choices=[('Anteproyecto', 'Anteproyecto'), ('Proyecto_final', 'Proyecto Final')], max_length=255),
        ),
    ]
