# Generated by Django 5.0.6 on 2024-09-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0017_alter_modelsolicitudes_relacionado_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('documento', models.BinaryField(blank=True, null=True)),
                ('fecha_cargue', models.CharField(max_length=50)),
            ],
        ),
    ]
