# Generated by Django 5.0.6 on 2024-09-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0018_modeldocumentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldocumentos',
            name='descripcion',
            field=models.CharField(default='este documento', max_length=500),
            preserve_default=False,
        ),
    ]
