# Generated by Django 5.0.6 on 2024-09-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0019_modeldocumentos_descripcion'),
        ('estudiante', '0021_alter_modelproyectofinal_anteproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='estudiante.modelanteproyecto'),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solicitudes', to='estudiante.modelanteproyecto'),
        ),
    ]
