# Generated by Django 5.0.6 on 2024-09-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0020_alter_modelinformacionentregafinal_anteproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldocumentos',
            name='fecha_cargue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='fecha_retroalimentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
