# Generated by Django 5.0.6 on 2024-10-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0021_alter_modeldocumentos_fecha_cargue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsolicitudes',
            name='relacionado_con',
        ),
    ]
