# Generated by Django 5.0.6 on 2024-10-01 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0022_remove_modelsolicitudes_relacionado_con'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelretroalimentaciones',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Retroalimentaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
