# Generated by Django 5.0.6 on 2024-10-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0023_modelretroalimentaciones_user'),
        ('estudiante', '0039_remove_modelproyectofinal_carta_presentacion_final_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelasignacionjurados'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelinformacionentregafinal',
            name='retroalimentaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Informacion_Entrega_Final', to='correspondencia.modelretroalimentaciones'),
        ),
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Retroalimentaciones', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solicitudes', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='retroalimentaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solicitudes', to='correspondencia.modelretroalimentaciones'),
        ),
        migrations.AlterField(
            model_name='modelsolicitudes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
