# Generated by Django 5.0.6 on 2024-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0024_alter_modelinformacionentregafinal_jurado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelretroalimentaciones',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='aprobado', max_length=25, null=True),
        ),
    ]
