# Generated by Django 5.0.6 on 2024-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0025_alter_modelretroalimentaciones_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFechasComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_primer_encuentro', models.DateTimeField(blank=True, null=True)),
                ('fecha_segundo_encuentro', models.DateTimeField(blank=True, null=True)),
                ('fecha_tercer_encuentro', models.DateTimeField(blank=True, null=True)),
                ('fecha_cuarto_encuentro', models.DateTimeField(blank=True, null=True)),
                ('fecha_extraordinaria', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
