# Generated by Django 5.0.6 on 2024-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0027_modelfechascomite_ano_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfechascomite',
            name='periodo_academico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
