# Generated by Django 5.0.6 on 2024-10-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0028_alter_modelfechascomite_periodo_academico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfechascomite',
            old_name='fecha_cuarto_encuentro',
            new_name='cuarto_encuentro',
        ),
        migrations.RenameField(
            model_name='modelfechascomite',
            old_name='fecha_extraordinaria',
            new_name='extraordinaria',
        ),
        migrations.RenameField(
            model_name='modelfechascomite',
            old_name='fecha_primer_encuentro',
            new_name='primer_encuentro',
        ),
        migrations.RenameField(
            model_name='modelfechascomite',
            old_name='fecha_segundo_encuentro',
            new_name='segundo_encuentro',
        ),
        migrations.RenameField(
            model_name='modelfechascomite',
            old_name='fecha_tercer_encuentro',
            new_name='tercer_encuentro',
        ),
    ]
