# Generated by Django 5.0.6 on 2024-10-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0029_rename_fecha_cuarto_encuentro_modelfechascomite_cuarto_encuentro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfechascomite',
            name='ano_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfechascomite',
            name='cuarto_encuentro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfechascomite',
            name='extraordinaria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfechascomite',
            name='primer_encuentro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfechascomite',
            name='segundo_encuentro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfechascomite',
            name='tercer_encuentro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
