# Generated by Django 5.0.6 on 2024-08-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
