# Generated by Django 5.0.6 on 2024-10-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_usuarios_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelerror',
            options={'verbose_name_plural': 'Errores'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
