# Generated by Django 5.0.6 on 2024-08-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuarios_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('fecha_hora_error', models.DateTimeField()),
            ],
        ),
    ]
