# Generated by Django 5.0.6 on 2024-10-17 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_modelerror_options_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelerror',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Error', to=settings.AUTH_USER_MODEL),
        ),
    ]
