# Generated by Django 5.0.6 on 2024-08-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_usuarios_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
