# Generated by Django 5.0.6 on 2024-08-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_usuarios_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
    ]
