# Generated by Django 5.0.6 on 2024-08-27 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='EtapasProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrimeraSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica', models.CharField(max_length=1000, verbose_name='Inscribe la temática a tratar')),
                ('lineas_inv', models.CharField(choices=[('IA', 'Inteligencia Artificial'), ('BD', 'Bases de Datos'), ('RS', 'Redes y Seguridad'), ('SI', 'Sistemas de Información'), ('DS', 'Desarrollo de Software')], max_length=255, verbose_name='Selecciona a que línea de investigación pertenece el proyecto')),
                ('problema', models.TextField(verbose_name='Problemática para tratar (máximo 500 palabras)')),
                ('num_integrantes', models.CharField(choices=[('1', '1 Integrante'), ('2', '2 Integrantes')], max_length=1, verbose_name='Selecciona el número de integrantes (máximo 2)')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAnteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('nombre_integrante1', models.CharField(max_length=200)),
                ('nombre_integrante2', models.CharField(max_length=200)),
                ('carta_presentacion', models.BinaryField(blank=True, null=True)),
                ('anteproyecto', models.BinaryField(blank=True, null=True)),
                ('director', models.CharField(max_length=200)),
                ('coodirector', models.CharField(max_length=200)),
                ('solicitud_enviada', models.BooleanField()),
                ('fecha_envio', models.CharField(max_length=200)),
                ('estado_solicitud_anteproyecto', models.BooleanField()),
                ('retroalimentacion', models.TextField()),
                ('rev_dadas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Anteproyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
