# Generated by Django 5.0.6 on 2024-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='rev_dadas',
            field=models.IntegerField(default=0),
        ),
    ]
