# Generated by Django 5.0.6 on 2024-08-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanteproyecto',
            name='enviado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
