# Generated by Django 5.1 on 2024-10-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_alter_modelobjetivosespecificos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfechasproyecto',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
