# Generated by Django 5.0.6 on 2024-08-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_alter_modelanteproyecto_coodirector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelanteproyecto',
            name='enviado',
        ),
    ]
