# Generated by Django 5.0.6 on 2024-08-28 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_remove_modelanteproyecto_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Anteproyecto', to=settings.AUTH_USER_MODEL),
        ),
    ]
