# Generated by Django 5.0.6 on 2024-09-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_rename_nombre_proyecto_modelanteproyecto_nombre_anteproyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelanteproyecto',
            name='rev_dadas',
        ),
    ]
