# Generated by Django 5.0.6 on 2024-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0008_remove_modelanteproyecto_rev_dadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanteproyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
