# Generated by Django 5.0.6 on 2024-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0009_modelanteproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
