# Generated by Django 5.0.6 on 2024-09-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0010_alter_modelanteproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
