# Generated by Django 5.0.6 on 2024-09-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0014_alter_modelanteproyecto_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproyectofinal',
            name='codirector',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
