# Generated by Django 5.0.6 on 2024-09-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0015_modelproyectofinal_codirector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelanteproyecto',
            old_name='coodirector',
            new_name='codirector',
        ),
    ]
