# Generated by Django 5.0.6 on 2024-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0016_rename_coodirector_modelanteproyecto_codirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanteproyecto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelproyectofinal',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
