# Generated by Django 5.0.6 on 2024-09-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0017_modelanteproyecto_estado_modelproyectofinal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproyectofinal',
            name='codirector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
