# Generated by Django 5.0.6 on 2024-09-10 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0018_alter_modelproyectofinal_codirector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproyectofinal',
            name='anteproyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Proyecto_Final', to='estudiante.modelanteproyecto'),
        ),
    ]
