# Generated by Django 5.0.6 on 2024-09-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0019_alter_modelproyectofinal_anteproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAsignacionJurados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jurado', models.CharField(max_length=50)),
                ('fecha_sustentacion', models.DateField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='modelproyectofinal',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Proyecto_Final', to='estudiante.modelasignacionjurados'),
        ),
    ]
