# Generated by Django 5.0.6 on 2024-09-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0021_alter_modelproyectofinal_anteproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.BooleanField(blank=True, default=False)),
                ('anteproyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_general', to='estudiante.modelanteproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ModelObjetivosEspecificos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.BooleanField(blank=True, default=False)),
                ('objetivo_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='estudiante.modelobjetivogeneral')),
            ],
        ),
        migrations.CreateModel(
            name='ModelActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('objetivos_especificos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='estudiante.modelobjetivosespecificos')),
            ],
        ),
    ]
