# Generated by Django 5.0.6 on 2024-09-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0022_modelobjetivogeneral_modelobjetivosespecificos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproyectofinal',
            name='director',
        ),
    ]
