# Generated by Django 5.0.6 on 2024-09-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0023_remove_modelproyectofinal_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproyectofinal',
            name='descripcion',
        ),
    ]
