# Generated by Django 5.0.6 on 2024-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0025_remove_modelproyectofinal_codirector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproyectofinal',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='modelproyectofinal',
            name='fecha_envio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelproyectofinal',
            name='solicitud_enviada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
