# Generated by Django 5.0.6 on 2024-09-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0026_alter_modelproyectofinal_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelproyectofinal',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
