# Generated by Django 5.0.6 on 2024-10-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0027_alter_modelanteproyecto_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='solicitud_enviada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
