# Generated by Django 5.0.6 on 2024-10-01 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0029_alter_modelanteproyecto_nombre_anteproyecto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='nombre_anteproyecto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Anteproyecto', to=settings.AUTH_USER_MODEL),
        ),
    ]
