# Generated by Django 5.0.6 on 2024-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0030_alter_modelanteproyecto_nombre_anteproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanteproyecto',
            name='documento_radicado',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelproyectofinal',
            name='documento_radicado',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
