# Generated by Django 5.0.6 on 2024-10-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0032_fechaproyecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FechaProyecto',
            new_name='ModelFechaProyecto',
        ),
    ]
