# Generated by Django 5.0.6 on 2024-10-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0034_rename_proyecto_modelfechaproyecto_proyecto_final'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelFechaProyecto',
            new_name='ModelFechasProyecto',
        ),
    ]
