# Generated by Django 5.0.6 on 2024-10-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0035_rename_modelfechaproyecto_modelfechasproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelobjetivogeneral',
            name='anteproyecto',
        ),
        migrations.AddField(
            model_name='modelobjetivogeneral',
            name='proyecto_final',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_general', to='estudiante.modelproyectofinal'),
        ),
    ]
