# Generated by Django 5.0.6 on 2024-10-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0037_remove_modelobjetivogeneral_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelactividades',
            name='objetivo_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='estudiante.modelobjetivogeneral'),
        ),
    ]
