# Generated by Django 5.0.6 on 2024-10-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0038_modelactividades_objetivo_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproyectofinal',
            name='carta_presentacion_final',
        ),
        migrations.RemoveField(
            model_name='modelproyectofinal',
            name='jurado',
        ),
        migrations.AddField(
            model_name='modelasignacionjurados',
            name='proyecto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jurados', to='estudiante.modelproyectofinal'),
        ),
        migrations.AlterField(
            model_name='modelasignacionjurados',
            name='fecha_sustentacion',
            field=models.DateField(),
        ),
    ]
