# Generated by Django 5.0.6 on 2024-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0039_remove_modelproyectofinal_carta_presentacion_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelobjetivosespecificos',
            name='documento_avance',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
