# Generated by Django 5.0.6 on 2024-10-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0040_modelobjetivosespecificos_documento_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanteproyecto',
            name='documento_concepto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelproyectofinal',
            name='carta_presentacion_final',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelproyectofinal',
            name='documento_concepto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
