# Generated by Django 5.0.6 on 2024-10-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0041_modelanteproyecto_documento_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelobjetivosespecificos',
            name='documento_correcciones',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelobjetivosespecificos',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelobjetivosespecificos',
            name='fecha_observacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelobjetivosespecificos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
