# Generated by Django 5.0.6 on 2024-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0043_modelproyectofinal_fecha_sustentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproyectofinal',
            name='fecha_sustentacion',
        ),
        migrations.AddField(
            model_name='modelfechasproyecto',
            name='fecha_sustentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
