# Generated by Django 5.0.6 on 2024-10-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0044_remove_modelproyectofinal_fecha_sustentacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfechasproyecto',
            old_name='fecha_sustentacion',
            new_name='fecha_presentacion',
        ),
    ]
