# Generated by Django 5.0.6 on 2024-10-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0045_rename_fecha_sustentacion_modelfechasproyecto_fecha_presentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfechasproyecto',
            old_name='fecha_presentacion',
            new_name='fecha_sustentacion',
        ),
    ]
