# Generated by Django 5.1 on 2024-10-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0046_rename_fecha_presentacion_modelfechasproyecto_fecha_sustentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='nombre_integrante1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelanteproyecto',
            name='nombre_integrante2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelobjetivosespecificos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
