# Generated by Django 5.0.6 on 2024-09-28 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0023_remove_modelproyectofinal_director'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluacionAnteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_anteproyectos', to='estudiante.modelanteproyecto')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_anteproyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEvaluacionProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos', to=settings.AUTH_USER_MODEL)),
                ('proyecto_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos', to='estudiante.modelproyectofinal')),
            ],
        ),
    ]
