# Generated by Django 5.0.6 on 2024-09-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevaluacionanteproyecto',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelevaluacionproyectofinal',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionanteproyecto',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionproyectofinal',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
