# Generated by Django 5.0.6 on 2024-09-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_modelevaluacionanteproyecto_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelevaluacionanteproyecto',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionanteproyecto',
            name='fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionproyectofinal',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionproyectofinal',
            name='fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
