# Generated by Django 5.0.6 on 2024-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_alter_modelevaluacionanteproyecto_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevaluacionanteproyecto',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='modelevaluacionproyectofinal',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
