# Generated by Django 5.0.6 on 2024-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_modelevaluacionanteproyecto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelevaluacionanteproyecto',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionproyectofinal',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
