# Generated by Django 5.0.6 on 2024-09-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_alter_modelevaluacionanteproyecto_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevaluacionanteproyecto',
            name='doc_evaluacion_anteproyecto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='modelevaluacionproyectofinal',
            name='doc_evaluacion_proyecto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
