# Generated by Django 5.0.6 on 2024-09-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_modelevaluacionanteproyecto_doc_evaluacion_anteproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelevaluacionanteproyecto',
            name='doc_evaluacion_anteproyecto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelevaluacionproyectofinal',
            name='doc_evaluacion_proyecto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
