# Generated by Django 5.0.6 on 2024-10-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0007_alter_modelevaluacionanteproyecto_doc_evaluacion_anteproyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelevaluacionproyectofinal',
            old_name='evaluador',
            new_name='jurado',
        ),
    ]
